title: olavihaapala.fi
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  drafts:
    title: Drafts
    output: true
excerpt_separator: ''
plugins_src:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
email: olavi.haapala@futurice.com
author: Olavi Haapala
description: A personal blog about development
paginate: 50
include: ['.well-known']
exclude: ['test', 'node_modules']
url: https://olavihaapala.fi
enforce_ssl: olavihaapala.fi
sass:
  style: compressed
plugins:
  - jekyll-feed
feed:
  path: feed.xml